version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node:/usr/src/app
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"